export type Category = 'deep' | 'fun' | 'memory' | 'game' | 'action' | 'spicy' | 'naughty';

export interface CardInfo {
  id: string;
  category: Category;
  text: string;
}
export const CARDS: CardInfo[] = [

  // ─── DEEP ───────────────────────────────────────────────────────────────────
  { id: '1', category: 'deep', text: 'What is a moment where you felt most loved by me?' },
  { id: '2', category: 'deep', text: 'When did you first realize you were falling for me?' },
  { id: '3', category: 'deep', text: 'What is a dream you have that you have never spoken out loud?' },
  { id: '4', category: 'deep', text: 'What is one thing you are afraid to lose about us?' },
  { id: '5', category: 'deep', text: 'When do you feel closest to me, even when we are far apart?' },
  { id: '6', category: 'deep', text: 'What is something you have been overthinking about us lately?' },
  { id: '7', category: 'deep', text: 'In what ways do you think we make each other better?' },
  { id: '8', category: 'deep', text: 'What is a fear you have right now about the future?' },
  { id: '9', category: 'deep', text: 'Do you think long distance has made us stronger or just harder? Why?' },
  { id: '10', category: 'deep', text: 'What is something about you that I still don\'t fully understand?' },
  { id: '11', category: 'deep', text: 'Do you think we would still choose each other if we met today as strangers?' },
  { id: '12', category: 'deep', text: 'What is something you have changed about yourself because of me?' },
  { id: '13', category: 'deep', text: 'What part of missing me do you never say out loud?' },
  { id: '14', category: 'deep', text: 'When do you feel most insecure in our relationship?' },
  { id: '15', category: 'deep', text: 'What is something you wish I understood about you without you having to explain it?' },
  { id: '16', category: 'deep', text: 'What is one version of our future you secretly hope for the most?' },
  { id: '17', category: 'deep', text: 'What is a conversation we have never had that you think we need to?' },
  { id: '18', category: 'deep', text: 'What emotion do I bring out in you that no one else ever has?' },

  // ─── FUN ────────────────────────────────────────────────────────────────────
  { id: '19', category: 'fun', text: 'If we could teleport anywhere for dinner tonight, where to?' },
  { id: '20', category: 'fun', text: 'If we were in a zombie apocalypse, what would be your survival role vs mine?' },
  { id: '21', category: 'fun', text: 'Which movie accurately describes our relationship?' },
  { id: '22', category: 'fun', text: 'If you had to describe my personality in 3 adjectives, what are they?' },
  { id: '23', category: 'fun', text: 'If we could only eat one meal together for the rest of our lives, what is it?' },
  { id: '24', category: 'fun', text: 'If we switched lives for a day, what is the first thing you would do as me?' },
  { id: '25', category: 'fun', text: 'What is the dumbest argument we have ever had?' },
  { id: '26', category: 'fun', text: 'If I was a video game character, what would my special ability be?' },
  { id: '27', category: 'fun', text: 'If we had a couple nickname that was embarrassing, what would it be?' },
  { id: '28', category: 'fun', text: 'What is something weird about me that you secretly love?' },
  { id: '29', category: 'fun', text: 'If our relationship was a startup, what would its biggest problem be?' },
  { id: '30', category: 'fun', text: 'If we had a reality show, what would it be called?' },
  { id: '31', category: 'fun', text: 'Which one of us would survive longer in a horror movie and why?' },
  { id: '32', category: 'fun', text: 'What is the most unserious thing about me that you love?' },
  { id: '33', category: 'fun', text: 'What is something I do that would get me cancelled if people saw it?' },
  { id: '34', category: 'fun', text: 'If you had to cast us in a rom-com, who plays who and what is the plot?' },

  // ─── GAME ───────────────────────────────────────────────────────────────────
  { id: '35', category: 'game', text: 'Staring contest. First to blink buys the next coffee!' },
  { id: '36', category: 'game', text: 'Thumb war! Loser gives a 5-minute massage.' },
  { id: '37', category: 'game', text: 'Rock, paper, scissors. Best 2 out of 3.' },
  { id: '38', category: 'game', text: 'Arm wrestle. Loser makes the bed tomorrow.' },
  { id: '39', category: 'game', text: 'Try not to laugh while I spend 30 seconds doing everything to make you crack.' },
  { id: '40', category: 'game', text: 'Guess what I am thinking right now. You get 3 tries.' },
  { id: '41', category: 'game', text: 'Say a word at the same time in 3…2…1. Try to match.' },
  { id: '42', category: 'game', text: 'Describe me in one word. I will do the same. Compare.' },
  { id: '43', category: 'game', text: 'First one to smile loses. Go.' },
  { id: '44', category: 'game', text: 'We both type a number from 1–10. If it matches, we win.' },
  { id: '45', category: 'game', text: 'We both type a place we want to visit together in 3…2…1. If it matches, we go someday.' },
  { id: '46', category: 'game', text: 'Guess my current mood in one word. I\'ll tell you if you\'re right.' },
  { id: '47', category: 'game', text: 'We both type what we think the other is craving right now. Reveal together.' },
  { id: '48', category: 'game', text: 'Think of a color. 3…2…1. Say it. Did we match?' },
  { id: '49', category: 'game', text: 'You have 10 seconds to make me smile. Start now.' },

  // ─── MEMORY ─────────────────────────────────────────────────────────────────
  { id: '50', category: 'memory', text: 'What was your first impression of me?' },
  { id: '51', category: 'memory', text: 'Describe exactly what I was wearing on our first date.' },
  { id: '52', category: 'memory', text: 'What is your favorite trip we\'ve ever taken together?' },
  { id: '53', category: 'memory', text: 'What\'s a small, random thing I did that stuck with you for a long time?' },
  { id: '54', category: 'memory', text: 'What is a random moment with me that still makes you smile?' },
  { id: '55', category: 'memory', text: 'When did I surprise you the most?' },
  { id: '56', category: 'memory', text: 'What is one small habit of mine you miss daily?' },
  { id: '57', category: 'memory', text: 'What was a moment where you felt I really understood you?' },
  { id: '58', category: 'memory', text: 'What is a moment with me you wish you could freeze forever?' },
  { id: '59', category: 'memory', text: 'When did you last re-read our old chats, and what made you do it?' },
  { id: '60', category: 'memory', text: 'What is something small I did that meant way more than I realized?' },
  { id: '61', category: 'memory', text: 'What was a moment you realized I mattered more than you expected?' },
  { id: '62', category: 'memory', text: 'What is a memory of us that still gives you butterflies?' },

  // ─── ACTION ─────────────────────────────────────────────────────────────────
  { id: '63', category: 'action', text: 'Send me a funny selfie right now.' },
  { id: '64', category: 'action', text: 'Kiss my forehead right now.' },
  { id: '65', category: 'action', text: 'Stare deeply into each other\'s eyes for exactly 1 minute.' },
  { id: '66', category: 'action', text: 'Give me your best pick-up line. You have 10 seconds to prepare.' },
  { id: '67', category: 'action', text: 'Send me a voice note describing how you would hug me right now.' },
  { id: '68', category: 'action', text: 'Close your eyes for 10 seconds and imagine me. Then tell me what you saw.' },
  { id: '69', category: 'action', text: 'Send me the last picture in your gallery without explaining it.' },
  { id: '70', category: 'action', text: 'Text me something you have never said before.' },
  { id: '71', category: 'action', text: 'Set a reminder for our next call and tell me what you are most excited for.' },
  { id: '72', category: 'action', text: 'Send me a 20-second voice note saying exactly what you feel right now.' },
  { id: '73', category: 'action', text: 'Type a message I can open the next time I miss you.' },
  { id: '74', category: 'action', text: 'Describe our next meeting in detail like it is happening right now.' },
  { id: '75', category: 'action', text: 'Send me a photo of something around you that reminds you of me.' },
  { id: '76', category: 'action', text: 'Write one sentence that would instantly make my day better.' },

  // ─── SPICY ──────────────────────────────────────────────────────────────────
  { id: '77', category: 'spicy', text: 'What is your favorite memory of us in the bedroom?' },
  { id: '78', category: 'spicy', text: 'What is a secret fantasy you have been too shy to share?' },
  { id: '79', category: 'spicy', text: 'What is your absolute favorite spot to be kissed?' },
  { id: '80', category: 'spicy', text: 'What is something I do that instantly gets your attention?' },
  { id: '81', category: 'spicy', text: 'What do you think I look best in — or without?' },
  { id: '82', category: 'spicy', text: 'What is one thing you want to do the next time we meet?' },
  { id: '83', category: 'spicy', text: 'What kind of kiss do you miss the most from me?' },
  { id: '84', category: 'spicy', text: 'What is something subtle I do that you find really attractive?' },
  { id: '85', category: 'spicy', text: 'What kind of moment between us do you replay the most in your head?' },
  { id: '86', category: 'spicy', text: 'What do you think I underestimate about my own attractiveness?' },
  { id: '87', category: 'spicy', text: 'What is one thing you would want to do slowly with me next time we meet?' },
  { id: '88', category: 'spicy', text: 'What kind of closeness do you miss the most right now?' },
  { id: '89', category: 'spicy', text: 'What is something you have imagined about us that you have not told me yet?' },
  { id: '90', category: 'spicy', text: 'Describe the last dream you had about me.' },
  { id: '109', category: 'spicy', text: 'If we were stuck in a lift together for 20 minutes, how would we spend the time?' },
  { id: '110', category: 'spicy', text: 'What is the most explicit thing you have ever thought about doing to me?' },

  // ─── NAUGHTY ────────────────────────────────────────────────────────────────
  { id: '91', category: 'naughty', text: 'Whisper something indecent in my ear.' },
  { id: '92', category: 'naughty', text: 'Where is the riskiest place you have ever wanted to do it?' },
  { id: '93', category: 'naughty', text: 'What article of my clothing drives you the craziest?' },
  { id: '94', category: 'naughty', text: 'If I was right in front of you right now, what is the first thing you would do?' },
  { id: '95', category: 'naughty', text: 'Describe how you would distract me if I was trying to focus.' },
  { id: '96', category: 'naughty', text: 'What is something you would whisper to me if no one could hear?' },
  { id: '97', category: 'naughty', text: 'What is your favorite way to tease me, and do you think it always works?' },
  { id: '98', category: 'naughty', text: 'What is something you want me to do more often?' },
  { id: '99', category: 'naughty', text: 'What is something you think about when you miss me late at night?' },
  { id: '100', category: 'naughty', text: 'What is one way you would try to distract me if we were completely alone together?' },
  { id: '101', category: 'naughty', text: 'What kind of teasing from me makes it hardest for you to keep your composure?' },
  { id: '102', category: 'naughty', text: 'If you could have me any way you wanted tonight, walk me through it.' },
  { id: '103', category: 'naughty', text: 'What do I do that makes it hard for you to keep your hands to yourself?' },
  { id: '104', category: 'naughty', text: 'Describe exactly how you would kiss me right now if you could.' },
  { id: '105', category: 'naughty', text: 'What is your biggest guilty pleasure when it comes to me?' },
  { id: '106', category: 'naughty', text: 'What would you do if you woke up and I was already next to you?' },
  { id: '107', category: 'naughty', text: 'What is one outfit you want to see me in — or out of?' },
  { id: '108', category: 'naughty', text: 'What is a scenario you have imagined about us that you have never admitted?' },
  { id: '111', category: 'naughty', text: 'Send me a photo of your favorite "view" of me, even if it\'s NSFW.' },
  { id: '112', category: 'naughty', text: 'Describe the exact sensations you want to feel the next time we are naked together.' },
  { id: '113', category: 'naughty', text: 'If you could use any toy or accessory on me, what would it be and how?' },
  { id: '114', category: 'naughty', text: 'What part of my body do you crave tasting the most right now?' },
  { id: '115', category: 'naughty', text: 'How do you like to be touched when you’re already on the edge?' },
  { id: '116', category: 'naughty', text: 'Tell me exactly what you want me to do to you until you can\'t take it anymore.' },
  { id: '117', category: 'naughty', text: 'What is your favorite position, and why does it feel the best with me?' },
  { id: '118', category: 'naughty', text: 'Describe a time you were thinking about me while you were "taking care" of yourself.' },
  { id: '119', category: 'naughty', text: 'If I told you to get on your knees right now, what would your response be?' },
  { id: '120', category: 'naughty', text: 'What is a dirty habit you have that you think would surprise me?' },
  { id: '121', category: 'deep', text: 'If you could rewrite one moment in our story, what would it be and why?' },
  { id: '122', category: 'deep', text: 'What is a version of yourself you only show me and no one else?' },
  { id: '123', category: 'deep', text: 'What is the quietest way I have ever hurt you without realizing it?' },
  { id: '124', category: 'deep', text: 'Do you think there is a version of us that exists in a parallel universe and got to be together sooner?' },
  { id: '125', category: 'deep', text: 'What is something about missing me that has changed you?' },
  { id: '126', category: 'deep', text: 'If our relationship had a theme song for this exact chapter, what would it be?' },
  { id: '127', category: 'deep', text: 'What is something you are scared to want because you are afraid it will not happen?' },
  { id: '128', category: 'deep', text: 'Is there a small thing I do that quietly tells you I love you without me saying it?' },
  { id: '129', category: 'deep', text: 'What is the hardest day you have had recently, and did you want to call me?' },
  { id: '130', category: 'deep', text: 'When you picture our life together years from now, what is the first image that comes?' },
  { id: '131', category: 'deep', text: 'Is there a time you felt like giving up on us? What kept you?' },
  { id: '132', category: 'deep', text: 'What is something I said once that you still think about?' },
  { id: '133', category: 'deep', text: 'How has loving me changed what you believe about yourself?' },
  { id: '134', category: 'deep', text: 'What is a boundary you have never told me about but quietly have?' },
  { id: '135', category: 'deep', text: 'What is the biggest sacrifice you have made for this relationship?' },
  { id: '136', category: 'deep', text: 'What is something you have never let yourself fully grieve about the distance between us?' },
  { id: '137', category: 'deep', text: 'If you had to describe what loving me feels like as a weather pattern, what is it?' },
  { id: '138', category: 'deep', text: 'What is a dream you have quietly stopped believing in and what would it take to start again?' },
  { id: '139', category: 'deep', text: 'What is a part of your day you save in your head to tell me about later?' },
  { id: '140', category: 'deep', text: 'What would you want me to know about you that even your closest friends do not know?' },
  { id: '141', category: 'fun', text: 'If our relationship was a Netflix series, what genre is it and are we renewed for another season?' },
  { id: '142', category: 'fun', text: 'What is the most unhinged text I have ever sent you that you secretly loved?' },
  { id: '143', category: 'fun', text: 'If you had to describe our relationship using only food, what are we?' },
  { id: '144', category: 'fun', text: 'What is the most embarrassing thing you have done to get my attention?' },
  { id: '145', category: 'fun', text: 'If I were a planet, which one and why?' },
  { id: '146', category: 'fun', text: 'What is a habit of mine that would absolutely annoy your parents if they found out?' },
  { id: '147', category: 'fun', text: 'If we competed on a cooking show together, what would go catastrophically wrong?' },
  { id: '148', category: 'fun', text: 'What is my most predictable behavior that you could set a clock to?' },
  { id: '149', category: 'fun', text: 'If I were a dog breed, which one fits me perfectly?' },
  { id: '150', category: 'fun', text: 'What is a word or phrase I use constantly that has now ruined you?' },
  { id: '151', category: 'fun', text: 'If our relationship had a mascot, what animal would it be and what is its name?' },
  { id: '152', category: 'fun', text: 'If you wrote a one-star review of me, what would it say?' },
  { id: '153', category: 'fun', text: 'What is the silliest reason you have ever been annoyed at me?' },
  { id: '154', category: 'fun', text: 'If we were in The Amazing Race together, what would be our biggest fight?' },
  { id: '155', category: 'fun', text: 'What is something I do that you pretend not to notice but absolutely clock every time?' },
  { id: '156', category: 'fun', text: 'If I was a meme, which one am I?' },
  { id: '157', category: 'fun', text: 'What is your honest hot take about something I love that you secretly disagree with?' },
  { id: '158', category: 'fun', text: 'If we had a joint bank account for chaos, what would I spend the most on?' },
  { id: '159', category: 'fun', text: 'What is one thing about me that would genuinely surprise my own mother?' },
  { id: '160', category: 'fun', text: 'If you had to get a tattoo of something that represents me, what is it and where does it go?' },
  { id: '161', category: 'game', text: 'We each type one word to start a story, back and forth. First one to get weird loses.' },
  { id: '162', category: 'game', text: '20 questions. I am thinking of something and you have yes or no only.' },
  { id: '163', category: 'game', text: 'Two truths and a lie. Go. I will guess which one is the lie.' },
  { id: '164', category: 'game', text: 'Song lyrics hot potato. I start, you finish the next line, no Googling.' },
  { id: '165', category: 'game', text: 'Name 5 things in your room right now in under 10 seconds. Go.' },
  { id: '166', category: 'game', text: 'Rapid fire. I ask, you answer in 3 words max. No pausing.' },
  { id: '167', category: 'game', text: 'We each type our ideal version of tomorrow in one sentence. Share and compare.' },
  { id: '168', category: 'game', text: 'Emoji story. Tell me about your day using only 5 emojis. I will guess what happened.' },
  { id: '169', category: 'game', text: 'Type the first word that comes to mind when I say: us.' },
  { id: '170', category: 'game', text: 'Best 2-out-of-3 would you rather. I ask, you answer, then we switch.' },
  { id: '171', category: 'game', text: 'We both type what we think the other person is doing right now. Reveal at the same time.' },
  { id: '172', category: 'game', text: 'Name something red in your room before I count to 5. 5... 4... 3...' },
  { id: '173', category: 'game', text: 'The alphabet game. We take turns naming things we will do together, one per letter, A to Z.' },
  { id: '174', category: 'game', text: 'Type a number between 1 and 100. Closer to mine without going over wins a forehead kiss.' },
  { id: '175', category: 'game', text: 'Mirror game. Whatever I type next, you type the exact opposite feeling.' },
  { id: '176', category: 'memory', text: 'What is the exact moment you knew this was real and not just a feeling?' },
  { id: '177', category: 'memory', text: 'What is the most random thing that reminds you of me in your everyday life?' },
  { id: '178', category: 'memory', text: 'What is something I said once as a joke that turned out to be true?' },
  { id: '179', category: 'memory', text: 'Describe the first time you heard my voice. What did you notice?' },
  { id: '180', category: 'memory', text: 'What is the longest we have gone without talking and what did that feel like?' },
  { id: '181', category: 'memory', text: 'What is a photo of us you wish existed but never got taken?' },
  { id: '182', category: 'memory', text: 'What is something from the early days of us that you miss?' },
  { id: '183', category: 'memory', text: 'What is a moment where I showed up for you when you did not even ask?' },
  { id: '184', category: 'memory', text: 'What was going through your head the first time you typed I love you?' },
  { id: '185', category: 'memory', text: 'What is a fight we had that you are glad we worked through?' },
  { id: '186', category: 'memory', text: 'What is a version of us from a year ago you would go back and reassure?' },
  { id: '187', category: 'memory', text: 'What is the strangest or funniest coincidence in our story?' },
  { id: '188', category: 'memory', text: 'What is a compliment I gave you once that you still think about?' },
  { id: '189', category: 'memory', text: 'What is the first trip or outing you remember planning together and how did it go?' },
  { id: '190', category: 'memory', text: 'What is one thing about the beginning of us that you want to hold onto forever?' },
  { id: '191', category: 'action', text: 'Record a 10-second voice note of complete silence just to feel like we are in the same room.' },
  { id: '192', category: 'action', text: 'Send me a screenshot of the last song you played without any context.' },
  { id: '193', category: 'action', text: 'Open your camera right now and take a photo of exactly where you are sitting. Send it.' },
  { id: '194', category: 'action', text: 'Type out a playlist name that describes your mood right now.' },
  { id: '195', category: 'action', text: 'Write me a letter to open the morning of the day we finally close the distance.' },
  { id: '196', category: 'action', text: 'Set a 1-minute timer and write me everything you feel without editing it.' },
  { id: '197', category: 'action', text: 'Find an old photo of yourself and send it. I want to see a version of you I never knew.' },
  { id: '198', category: 'action', text: 'Send me a voice note reading your favorite line from a book, show, or song.' },
  { id: '199', category: 'action', text: 'Look around and send me a photo of the thing closest to you right now.' },
  { id: '200', category: 'action', text: 'Type a one-sentence promise you are making to me right now.' },
  { id: '201', category: 'action', text: 'Send me a voice note of you saying good night in the most dramatic way you can.' },
  { id: '202', category: 'action', text: 'Type the name of the restaurant I have to take you to the moment we are in the same city.' },
  { id: '203', category: 'action', text: 'Screenshot a moment from your camera roll that made you think of me recently. Send it without explanation.' },
  { id: '204', category: 'action', text: 'Type a word that describes how you feel when you hear my name.' },
  { id: '205', category: 'action', text: 'Write the opening line of the story of us, as if it were the first page of a book.' },
  { id: '206', category: 'spicy', text: 'What is the most attractive thing about me that has absolutely nothing to do with looks?' },
  { id: '207', category: 'spicy', text: 'What is a look I give you that makes it genuinely difficult to stay composed?' },
  { id: '208', category: 'spicy', text: 'What is the most charged moment between us that we never acted on?' },
  { id: '209', category: 'spicy', text: 'If you had to seduce me using only words, what is the first sentence?' },
  { id: '210', category: 'spicy', text: 'What do I do with my voice that you find secretly electric?' },
  { id: '211', category: 'spicy', text: 'What is the most tension you have ever felt between us without anything happening?' },
  { id: '212', category: 'spicy', text: 'If you could feel my presence for just 5 minutes right now, how would you use it?' },
  { id: '213', category: 'spicy', text: 'What is the most attractive thing I have ever done completely by accident?' },
  { id: '214', category: 'spicy', text: 'What part of me do you think about when you are trying to focus on something else?' },
  { id: '215', category: 'spicy', text: 'What is something about the way I text that gets under your skin in the best way?' },
  { id: '216', category: 'spicy', text: 'If the distance disappeared for one night, what is the first thing we would not do?' },
  { id: '217', category: 'spicy', text: 'What is a version of me in your imagination that you have never told me about?' },
  { id: '218', category: 'spicy', text: 'What kind of tension between us do you love to build and not release?' },
  { id: '219', category: 'spicy', text: 'What does it feel like in your body when I tell you I miss you?' },
  { id: '220', category: 'spicy', text: 'If I showed up at your door right now at midnight, what would your face do before your words?' },
  { id: '221', category: 'spicy', text: 'What is something I wear or do that makes you forget what you were saying?' },
  { id: '222', category: 'spicy', text: 'What would it feel like to finally fall asleep in the same bed as me?' },
  { id: '223', category: 'spicy', text: 'What is the single most physically attractive moment you can remember between us?' },
  { id: '224', category: 'spicy', text: 'What is something you would want to do slowly and quietly together that is completely innocent but somehow deeply intimate?' },
  { id: '225', category: 'spicy', text: 'If you could hear my heartbeat right now, what do you imagine it sounds like?' },
  { id: '226', category: 'naughty', text: 'What is the filthiest thought you have had about me this week?' },
  { id: '227', category: 'naughty', text: 'Describe in explicit detail exactly how you would take my clothes off if you were here.' },
  { id: '228', category: 'naughty', text: 'What is a sound you want to hear me make that you have not heard yet?' },
  { id: '229', category: 'naughty', text: 'Walk me through exactly what you would do to me if I told you I had 30 minutes and no one else home.' },
  { id: '230', category: 'naughty', text: 'What is the dirtiest thing you have ever wanted to say to me mid-act but held back?' },
  { id: '231', category: 'naughty', text: 'If I sent you a photo right now that was completely unfiltered, what would you ask me to do next?' },
  { id: '232', category: 'naughty', text: 'Describe the most explicit dream you have had about me in as much detail as you remember.' },
  { id: '233', category: 'naughty', text: 'What is something specific about my body that makes you lose control of your thoughts?' },
  { id: '234', category: 'naughty', text: 'If you could have me in any position for as long as you wanted, what are you choosing and why?' },
  { id: '235', category: 'naughty', text: 'What would you do to me if you knew I was already worked up before you even touched me?' },
  { id: '236', category: 'naughty', text: 'What is the most explicit voice note you have ever wanted to send me?' },
  { id: '237', category: 'naughty', text: 'Where exactly would your hands go first if no one was watching and we had all the time in the world?' },
  { id: '238', category: 'naughty', text: 'What is something specific you want to do to me that requires no rush and no clothes?' },
  { id: '239', category: 'naughty', text: 'Describe what you want me to do with my mouth right now.' },
  { id: '240', category: 'naughty', text: 'What is the exact phrase you would whisper to me in the dark that would completely undo me?' },
  { id: '241', category: 'naughty', text: 'What is your most indulgent fantasy about us that you replay when you are alone?' },
  { id: '242', category: 'naughty', text: 'If I gave you full permission to do whatever you wanted to me for one hour, give me the unedited version.' },
  { id: '243', category: 'naughty', text: 'What is the most explicit compliment you have been too shy to say out loud?' },
  { id: '244', category: 'naughty', text: 'What would you want to hear me say while you are touching me?' },
  { id: '245', category: 'naughty', text: 'What is something you want to try with me that you have never tried with anyone else?' },
  { id: '246', category: 'naughty', text: 'Describe what finishing together would look and feel like in as much detail as you want.' },
  { id: '247', category: 'naughty', text: 'What is the most specific body part you want your mouth on and what exactly would you do?' },
  { id: '248', category: 'naughty', text: 'If I called you right now completely out of breath, what do you think would have just happened?' },
  { id: '249', category: 'naughty', text: 'What is the scenario you replay most when you are taking care of yourself and I am the reason?' },
  { id: '250', category: 'naughty', text: 'Write me a short paragraph of the filthiest thing you want to do to me the second the distance is gone.' },

  // ─── NEW DEEP ─────────────────────────────────────────────────────────────
  { id: '251', category: 'deep', text: 'What is a belief about love you had before me that I completely shattered?' },
  { id: '252', category: 'deep', text: 'When was the last time you cried because of how much you love me?' },
  { id: '253', category: 'deep', text: 'What is something about you that you think I would leave me for if I found out?' },
  { id: '254', category: 'deep', text: 'If we never worked out, what would you want me to know about why it was still worth it?' },
  { id: '255', category: 'deep', text: 'What is your honest, unfiltered expectation of what our life will look like in 5 years?' },
  { id: '256', category: 'deep', text: 'What is a part of your life I am not included in that you hold onto secretly?' },
  { id: '257', category: 'deep', text: 'What is something you have forgiven me for that you have not told me about?' },
  { id: '258', category: 'deep', text: 'If I died tomorrow, what is the one thing you would want to have told me but never did?' },
  { id: '259', category: 'deep', text: 'What is a promise you made to yourself about this relationship that you have not told me?' },
  { id: '260', category: 'deep', text: 'What is the most vulnerable thing you have ever said to me and how did it feel?' },
  { id: '261', category: 'deep', text: 'What is something you pretend not to care about but secretly keeps you up at night?' },
  { id: '262', category: 'deep', text: 'Do you actually believe we are going to work out long-term? Be honest.' },
  { id: '263', category: 'deep', text: 'What is the worst thing you have ever thought about doing when you are mad at me?' },
  { id: '264', category: 'deep', text: 'What is a moment where you almost gave up on us but could not?' },
  { id: '265', category: 'deep', text: 'What is something you are jealous of other couples for that we do not have?' },
  { id: '266', category: 'deep', text: 'What is your biggest insecurity about this relationship?' },
  { id: '267', category: 'deep', text: 'If we had to go back to the beginning knowing what you know now, would you still choose me?' },
  { id: '268', category: 'deep', text: 'What is something you have stopped wanting because it feels impossible with the distance?' },
  { id: '269', category: 'deep', text: 'What is the most beautiful thing someone has ever said to you that was not me?' },
  { id: '270', category: 'deep', text: 'What is a conversation with me that changed something fundamental about you?' },

  // ─── NEW FUN ─────────────────────────────────────────────────────────────
  { id: '271', category: 'fun', text: 'If we were characters in a horror movie, what cheap line would I say right before dying?' },
  { id: '272', category: 'fun', text: 'What is the most unhinged thing on your search history right now?' },
  { id: '273', category: 'fun', text: 'If you made me a dating profile bio, what is the most embarrassing line?' },
  { id: '274', category: 'fun', text: 'What is a rumor you would start about us if you wanted to mess with people?' },
  { id: '275', category: 'fun', text: 'If I was a超级英雄, what would my pathetic weakness be?' },
  { id: '276', category: 'fun', text: 'What is the most worthless skill you have that somehow you are proud of?' },
  { id: '277', category: 'fun', text: 'If we had a kids show, what would the theme song be about?' },
  { id: '278', category: 'fun', text: 'What is the most cringe thing in your camera roll right now?' },
  { id: '279', category: 'fun', text: 'If I replaced all my clothes with oneitem, what would it be and why?' },
  { id: '280', category: 'fun', text: 'What is the weirdest thing you do when you think I am not watching?' },
  { id: '281', category: 'fun', text: 'If we were forced to do a podcast about us, what would be the most ridiculous episode title?' },
  { id: '282', category: 'fun', text: 'What is a lie you told me that I rightfully called out?' },
  { id: '283', category: 'fun', text: 'If you could replace me with an AI version, what would be its one fatal flaw?' },
  { id: '284', category: 'fun', text: 'What is your most unnecessary strong opinion about something completely random?' },
  { id: '285', category: 'fun', text: 'If we made a drinking game every time I do my most annoying habit, how would we not die?' },
  { id: '286', category: 'fun', text: 'What is the worst gift you have ever gotten for me that you pretended to love?' },
  { id: '287', category: 'fun', text: 'If I was a food, what shameful fast food item would I be and why?' },
  { id: '288', category: 'fun', text: 'What is the most ridiculous thing you have Googled "near me" in the last week?' },
  { id: '289', category: 'fun', text: 'If we had to elope, what is the one thing that would definitely go wrong first?' },
  { id: '290', category: 'fun', text: 'What is something you are irrationally competitive with me about?' },

  // ─── NEW NAUGHTY ─────────────────────────────────────────────────────
  { id: '291', category: 'naughty', text: 'What is your go-to fantasy when you are alone that you have never told me?' },
  { id: '292', category: 'naughty', text: 'Describe exactly what you would do if we were stuck together for 24 hours with nothing to do.' },
  { id: '293', category: 'naughty', text: 'What is the most intimate thing you have ever done in a public place?' },
  { id: '294', category: 'naughty', text: 'If you could control my body for 10 minutes, what would you make me do?' },
  { id: '295', category: 'naughty', text: 'What is the longest you have ever edged and why was it for me?' },
  { id: '296', category: 'naughty', text: 'Describe in detail what you want to do to every single part of my body.' },
  { id: '297', category: 'naughty', text: 'What is something about sex with me that you have never said out loud but want me to know?' },
  { id: '298', category: 'naughty', text: 'Error Card' },
  { id: '299', category: 'naughty', text: 'What costume or outfit do you want to see me in that is not for any occasion?' },
  { id: '300', category: 'naughty', text: 'What is your favorite way to be touched and how do you want me to do it right now?' },
  { id: '301', category: 'naughty', text: 'Describe exactly what you would do if we had all night with zero interruptions.' },
  { id: '302', category: 'naughty', text: 'What is the most sexually frustrating thing about the distance for you?' },
  { id: '303', category: 'naughty', text: 'What is the last thing you thought about before you fell asleep last night involving me?' },
  { id: '304', category: 'naughty', text: 'If I was inside you right now, what position would you want us in and what would you want to say?' },
  { id: '305', category: 'naughty', text: 'What part of my body do you want to taste the most and what exactly would you do with it?' },
  { id: '306', category: 'naughty', text: 'Tell me exactly how you would make love to me slowly from start to finish.' },
  { id: '307', category: 'naughty', text: 'What is the naughtiest thing you want to whisper in my ear while we do it?' },
  { id: '308', category: 'naughty', text: 'What toy would you want to use on me first and how would you use it?' },
  { id: '309', category: 'naughty', text: 'How many times have you came thinking about me this month? Be honest.' },
  { id: '310', category: 'naughty', text: 'What is your favorite time of day to do it and why?' },
  { id: '311', category: 'naughty', text: 'Describe what you want our first time to be like when we finally meet.' },
  { id: '312', category: 'naughty', text: 'What is a kink you have that you want to explore with me?' },
  { id: '313', category: 'naughty', text: 'What would you do if I sent you a spicy photo right now?' },
  { id: '314', category: 'naughty', text: 'What position are we doing the moment we are together and why?' },
  { id: '315', category: 'naughty', text: 'Where is the dirtiest place we could possibly do it and would we risk it?' },
  { id: '316', category: 'naughty', text: 'What sound do you most want to hear me make in bed?' },
  { id: '317', category: 'naughty', text: 'Tell me exactly what you would do if I slept over at your place tonight.' },
  { id: '318', category: 'naughty', text: 'What is your ultimate fantasy involving both of us?' },
  { id: '319', category: 'naughty', text: 'How do you want me to dominate you?' },
{ id: '320', category: 'naughty', text: 'What is your count and how many times can you make me finish?' },

  // ─── MORE FUN ─────────────────────────────────────────────────────────────
  { id: '321', category: 'fun', text: 'If we had a couple Instagram, what would our most embarrassing post be?' },
  { id: '322', category: 'fun', text: 'What is the most stupid reason you have ever been mad at me?' },
  { id: '323', category: 'fun', text: 'If I was a potato, what type of potato would I be and why?' },
  { id: '324', category: 'fun', text: 'What would our wedding cake look like if it was designed by a toddler?' },
  { id: '325', category: 'fun', text: 'If you had to explain our relationship to an alien, which pop culture reference would you use?' },
  { id: '326', category: 'fun', text: 'What is the most ridiculous thing you have typed to me and then deleted?' },
  { id: '327', category: 'fun', text: 'If we made a TikTok, what would its description say?' },
  { id: '328', category: 'fun', text: 'What is my most predictable bad habit that I refuse to admit?' },
  { id: '329', category: 'fun', text: 'If we competed in the Olympics of relationships, what event would we absolutely win?' },
  { id: '330', category: 'fun', text: 'What is the weirdest thing you have eaten just because I recommended it?' },
  { id: '331', category: 'fun', text: 'If we were in a reality TV show, what dramatic thing would happen in episode 3?' },
  { id: '332', category: 'fun', text: 'What is a phrase I say that has become hauntingly in your head?' },
  { id: '333', category: 'fun', text: 'If I was a video game, what difficulty level would I be on and why?' },
  { id: '334', category: 'fun', text: 'What is the most chaos-inducing thing you would do if I gave you my phone for 5 minutes?' },
  { id: '335', category: 'fun', text: 'If we had a joint bank account for dates, what would be the weirdest purchase we would make?' },
  { id: '336', category: 'fun', text: 'What is one thing about me that would make my future kids confused about?' },
  { id: '337', category: 'fun', text: 'If we met on a dating app, what would your opening line be?' },
  { id: '338', category: 'fun', text: 'What is the most unhinged thing you have done while missing me?' },
  { id: '339', category: 'fun', text: 'If we were cartoon characters, what would our catchphrase be?' },
  { id: '340', category: 'fun', text: 'What is something I do that would make a psychologist concerned?' },
  { id: '341', category: 'fun', text: 'If I was a smell, what would I smell like and it is not a compliment?' },
  { id: '342', category: 'fun', text: 'What is the worst "we were thinking about each other" text you have ever sent?' },
  { id: '343', category: 'fun', text: 'If we had a couples costume, what would it be and which one of us would complain more?' },
  { id: '344', category: 'fun', text: 'What is something I do that works on you but should not?' },
  { id: '345', category: 'fun', text: 'If you could make one of my habits a crime, what would be the punishment?' },
  { id: '346', category: 'fun', text: 'What is the most embarrassing notification sound you have set for me and do not lie?' },
  { id: '347', category: 'fun', text: 'If our love story was a trilogy, what would the second movie be called and it has to be cheesy?' },
  { id: '348', category: 'fun', text: 'What is the pettiest reason you have ever been mad at me?' },
  { id: '349', category: 'fun', text: 'If we lived in a sitcom, what would be the episode where everything goes wrong?' },
  { id: '350', category: 'fun', text: 'What is something I do when I think you are not looking that you act like you did not see?' },

  // ─── MORE NAUGHTY ─────────────────────────────────────────────────────
  { id: '351', category: 'naughty', text: 'What is the spiciest thing you want to whisper in my ear before we start?' },
  { id: '352', category: 'naughty', text: 'If you could only touch one part of my body for the rest of the night, what do you choose?' },
  { id: '353', category: 'naughty', text: 'Describe exactly how you would tease me until I beg.' },
  { id: '354', category: 'naughty', text: 'What is your favorite dirty word and why does it work on you?' },
  { id: '355', category: 'naughty', text: 'If we did it in front of a mirror, what would you want to see?' },
  { id: '356', category: 'naughty', text: 'What is your favorite place on my body to kiss and how hard?' },
  { id: '357', category: 'naughty', text: 'What is the boldest thing you have ever done when we were on video call?' },
  { id: '358', category: 'naughty', text: 'Describe what you would do if I told you I cannot sleep until you help.' },
  { id: '359', category: 'naughty', text: 'What is the naughtiest thing you have ever done in your parents house when they were home?' },
  { id: '360', category: 'naughty', text: 'If you could make a custom toy for us, what would it look like and how would it work?' },
  { id: '361', category: 'naughty', text: 'What is your favorite way to wake me up and does it involve clothes?' },
  { id: '362', category: 'naughty', text: 'Describe what you would do if I seductively walked toward you right now.' },
  { id: '363', category: 'naughty', text: 'What is the hottest text conversation you have ever saved?' },
  { id: '364', category: 'naughty', text: 'If you had one hour alone with me, how would you spend those 60 minutes?' },
  { id: '365', category: 'naughty', text: 'What is something you want to do to me that you think about when you should be sleeping?' },
  { id: '366', category: 'naughty', text: 'Tell me exactly what to do to you and I will do my best to follow instructions.' },
  { id: '367', category: 'naughty', text: 'What is the quickest way you have ever gotten turned on by just a text from me?' },
  { id: '368', category: 'naughty', text: 'Describe the hottest dream you have ever had about us.' },
  { id: '369', category: 'naughty', text: 'What is your favorite position to finish in and why does it hit different?' },
  { id: '370', category: 'naughty', text: 'If I was blindfolded, where would you touch first and what would you whisper?' },
  { id: '371', category: 'naughty', text: 'What is the messiest we have ever gotten and what was the clean up like?' },
  { id: '372', category: 'naughty', text: 'Describe exactly what you want to do to me after we have not seen each other for a while.' },
  { id: '373', category: 'naughty', text: 'What is your favorite outfit of mine to take off and in what order?' },
  { id: '374', category: 'naughty', text: 'How long can you last if I do not stop and why will it be hard?' },
  { id: '375', category: 'naughty', text: 'What is that one specific thing I do with my hands that destroys you?' },
  { id: '376', category: 'naughty', text: 'If I video called you right now ready to go, what is the first thing you do?' },
  { id: '377', category: 'naughty', text: 'What is the dirtiest sentence I have ever said to you that still makes you blush?' },
  { id: '378', category: 'naughty', text: 'Describe the perfect night in with me from the moment I walk in the door.' },
  { id: '379', category: 'naughty', text: 'What is your count and be honest, how many times this week alone?' },
  { id: '380', category: 'naughty', text: 'Where would you leave the hickey that would get me in trouble at work?' },

];