export type Category = 'deep' | 'fun' | 'memory' | 'game' | 'action' | 'spicy' | 'naughty';

export interface CardInfo {
  id: string;
  category: Category;
  text: string;
}

export const CARDS: CardInfo[] = [
  { id: '1', category: 'deep', text: 'What is a moment where you felt most loved by me?' },
  { id: '2', category: 'deep', text: 'When did you first realize you were falling for me?' },
  { id: '3', category: 'deep', text: 'What is a dream you have that you have never spoken out loud?' },
  { id: '4', category: 'deep', text: 'What is one thing you are afraid to lose about us?' },
  { id: '5', category: 'deep', text: 'When do you feel closest to me, even when we are far apart?' },
  { id: '6', category: 'deep', text: 'What is something you have been overthinking about us lately?' },
  { id: '7', category: 'deep', text: 'In what ways do you think we make each other better?' },
  { id: '8', category: 'deep', text: 'What is a fear you have right now about the future?' },
  { id: '9', category: 'deep', text: 'Do you think long distance has made us stronger or just harder? Why?' },
  { id: '10', category: 'deep', text: 'What is something about you that I still don\'t fully understand?' },
  { id: '11', category: 'deep', text: 'Do you think we would still choose each other if we met today as strangers?' },
  { id: '12', category: 'deep', text: 'What is something you have changed about yourself because of me?' },
  { id: '13', category: 'deep', text: 'What part of missing me do you never say out loud?' },
  { id: '14', category: 'deep', text: 'When do you feel most insecure in our relationship?' },
  { id: '15', category: 'deep', text: 'What is something you wish I understood about you without you having to explain it?' },
  { id: '16', category: 'deep', text: 'What is one version of our future you secretly hope for the most?' },
  { id: '17', category: 'deep', text: 'What is a conversation we have never had that you think we need to?' },
  { id: '18', category: 'deep', text: 'What emotion do I bring out in you that no one else ever has?' },

  { id: '19', category: 'fun', text: 'If we could teleport anywhere for dinner tonight, where to?' },
  { id: '20', category: 'fun', text: 'If we were in a zombie apocalypse, what would be your survival role vs mine?' },
  { id: '21', category: 'fun', text: 'Which movie accurately describes our relationship?' },
  { id: '22', category: 'fun', text: 'If you had to describe my personality in 3 adjectives, what are they?' },
  { id: '23', category: 'fun', text: 'If we could only eat one meal together for the rest of our lives, what is it?' },
  { id: '24', category: 'fun', text: 'If we switched lives for a day, what is the first thing you would do as me?' },
  { id: '25', category: 'fun', text: 'What is the dumbest argument we have ever had?' },
  { id: '26', category: 'fun', text: 'If I was a video game character, what would my special ability be?' },
  { id: '27', category: 'fun', text: 'If we had a couple nickname that was embarrassing, what would it be?' },
  { id: '28', category: 'fun', text: 'What is something weird about me that you secretly love?' },
  { id: '29', category: 'fun', text: 'If our relationship was a startup, what would its biggest problem be?' },
  { id: '30', category: 'fun', text: 'If we had a reality show, what would it be called?' },
  { id: '31', category: 'fun', text: 'Which one of us would survive longer in a horror movie and why?' },
  { id: '32', category: 'fun', text: 'What is the most unserious thing about me that you love?' },
  { id: '33', category: 'fun', text: 'What is something I do that would get me cancelled if people saw it?' },
  { id: '34', category: 'fun', text: 'If you had to cast us in a rom-com, who plays who and what is the plot?' },

  { id: '35', category: 'game', text: 'Staring contest. First to blink buys the next coffee!' },
  { id: '36', category: 'game', text: 'Thumb war! Loser gives a 5-minute massage.' },
  { id: '37', category: 'game', text: 'Rock, paper, scissors. Best 2 out of 3.' },
  { id: '38', category: 'game', text: 'Arm wrestle. Loser makes the bed tomorrow.' },
  { id: '39', category: 'game', text: 'Try not to laugh while I spend 30 seconds doing everything to make you crack.' },
  { id: '40', category: 'game', text: 'Guess what I am thinking right now. You get 3 tries.' },
  { id: '41', category: 'game', text: 'Say a word at the same time in 3…2…1. Try to match.' },
  { id: '42', category: 'game', text: 'Describe me in one word. I will do the same. Compare.' },
  { id: '43', category: 'game', text: 'First one to smile loses. Go.' },
  { id: '44', category: 'game', text: 'We both type a number from 1–10. If it matches, we win.' },
  { id: '45', category: 'game', text: 'We both type a place we want to visit together in 3…2…1. If it matches, we go someday.' },
  { id: '46', category: 'game', text: 'Guess my current mood in one word. I\'ll tell you if you\'re right.' },
  { id: '47', category: 'game', text: 'We both type what we think the other is craving right now. Reveal together.' },
  { id: '48', category: 'game', text: 'Think of a color. 3…2…1. Say it. Did we match?' },
  { id: '49', category: 'game', text: 'You have 10 seconds to make me smile. Start now.' },

  { id: '50', category: 'memory', text: 'What was your first impression of me?' },
  { id: '51', category: 'memory', text: 'Describe exactly what I was wearing on our first date.' },
  { id: '52', category: 'memory', text: 'What is your favorite trip we\'ve ever taken together?' },
  { id: '53', category: 'memory', text: 'What\'s a small, random thing I did that stuck with you for a long time?' },
  { id: '54', category: 'memory', text: 'What is a random moment with me that still makes you smile?' },
  { id: '55', category: 'memory', text: 'When did I surprise you the most?' },
  { id: '56', category: 'memory', text: 'What is one small habit of mine you miss daily?' },
  { id: '57', category: 'memory', text: 'What was a moment where you felt I really understood you?' },
  { id: '58', category: 'memory', text: 'What is a moment with me you wish you could freeze forever?' },
  { id: '59', category: 'memory', text: 'When did you last re-read our old chats, and what made you do it?' },
  { id: '60', category: 'memory', text: 'What is something small I did that meant way more than I realized?' },
  { id: '61', category: 'memory', text: 'What was a moment you realized I mattered more than you expected?' },
  { id: '62', category: 'memory', text: 'What is a memory of us that still gives you butterflies?' },

  { id: '63', category: 'action', text: 'Send me a funny selfie right now.' },
  { id: '64', category: 'action', text: 'Kiss my forehead right now.' },
  { id: '65', category: 'action', text: 'Stare deeply into each other\'s eyes for exactly 1 minute.' },
  { id: '66', category: 'action', text: 'Give me your best pick-up line. You have 10 seconds to prepare.' },
  { id: '67', category: 'action', text: 'Send me a voice note describing how you would hug me right now.' },
  { id: '68', category: 'action', text: 'Close your eyes for 10 seconds and imagine me. Then tell me what you saw.' },
  { id: '69', category: 'action', text: 'Send me the last picture in your gallery without explaining it.' },
  { id: '70', category: 'action', text: 'Text me something you have never said before.' },
  { id: '71', category: 'action', text: 'Set a reminder for our next call and tell me what you are most excited for.' },
  { id: '72', category: 'action', text: 'Send me a 20-second voice note saying exactly what you feel right now.' },
  { id: '73', category: 'action', text: 'Type a message I can open the next time I miss you.' },
  { id: '74', category: 'action', text: 'Describe our next meeting in detail like it is happening right now.' },
  { id: '75', category: 'action', text: 'Send me a photo of something around you that reminds you of me.' },
  { id: '76', category: 'action', text: 'Write one sentence that would instantly make my day better.' },
];