export type Category = 'deep' | 'fun' | 'memory' | 'game' | 'action' | 'spicy' | 'naughty';

export interface CardInfo {
  id: string;
  category: Category;
  text: string;
}

export const CARDS: CardInfo[] = [
  // DEEP (continued)
  { id: '121', category: 'deep', text: 'If you could rewrite one moment in our story, what would it be and why?' },
  { id: '122', category: 'deep', text: 'What is a version of yourself you only show me and no one else?' },
  { id: '123', category: 'deep', text: 'What is the quietest way I have ever hurt you without realizing it?' },
  { id: '124', category: 'deep', text: 'Do you think there is a version of us that exists in a parallel universe and got to be together sooner?' },
  { id: '125', category: 'deep', text: 'What is something about missing me that has changed you?' },
  { id: '126', category: 'deep', text: 'If our relationship had a theme song for this exact chapter, what would it be?' },
  { id: '127', category: 'deep', text: 'What is something you are scared to want because you are afraid it will not happen?' },
  { id: '128', category: 'deep', text: 'Is there a small thing I do that quietly tells you I love you without me saying it?' },
  { id: '129', category: 'deep', text: 'What is the hardest day you have had recently, and did you want to call me?' },
  { id: '130', category: 'deep', text: 'When you picture our life together years from now, what is the first image that comes?' },
  { id: '131', category: 'deep', text: 'Is there a time you felt like giving up on us? What kept you?' },
  { id: '132', category: 'deep', text: 'What is something I said once that you still think about?' },
  { id: '133', category: 'deep', text: 'How has loving me changed what you believe about yourself?' },
  { id: '134', category: 'deep', text: 'What is a boundary you have never told me about but quietly have?' },
  { id: '135', category: 'deep', text: 'What is the biggest sacrifice you have made for this relationship?' },
  { id: '136', category: 'deep', text: 'What is something you have never let yourself fully grieve about the distance between us?' },
  { id: '137', category: 'deep', text: 'If you had to describe what loving me feels like as a weather pattern, what is it?' },
  { id: '138', category: 'deep', text: 'What is a dream you have quietly stopped believing in and what would it take to start again?' },
  { id: '139', category: 'deep', text: 'What is a part of your day you save in your head to tell me about later?' },
  { id: '140', category: 'deep', text: 'What would you want me to know about you that even your closest friends do not know?' },

  // FUN (continued)
  { id: '141', category: 'fun', text: 'If our relationship was a Netflix series, what genre is it and are we renewed for another season?' },
  { id: '142', category: 'fun', text: 'What is the most unhinged text I have ever sent you that you secretly loved?' },
  { id: '143', category: 'fun', text: 'If you had to describe our relationship using only food, what are we?' },
  { id: '144', category: 'fun', text: 'What is the most embarrassing thing you have done to get my attention?' },
  { id: '145', category: 'fun', text: 'If I were a planet, which one and why?' },
  { id: '146', category: 'fun', text: 'What is a habit of mine that would absolutely annoy your parents if they found out?' },
  { id: '147', category: 'fun', text: 'If we competed on a cooking show together, what would go catastrophically wrong?' },
  { id: '148', category: 'fun', text: 'What is my most predictable behavior that you could set a clock to?' },
  { id: '149', category: 'fun', text: 'If I were a dog breed, which one fits me perfectly?' },
  { id: '150', category: 'fun', text: 'What is a word or phrase I use constantly that has now ruined you?' },
  { id: '151', category: 'fun', text: 'If our relationship had a mascot, what animal would it be and what is its name?' },
  { id: '152', category: 'fun', text: 'If you wrote a one-star review of me, what would it say?' },
  { id: '153', category: 'fun', text: 'What is the silliest reason you have ever been annoyed at me?' },
  { id: '154', category: 'fun', text: 'If we were in The Amazing Race together, what would be our biggest fight?' },
  { id: '155', category: 'fun', text: 'What is something I do that you pretend not to notice but absolutely clock every time?' },
  { id: '156', category: 'fun', text: 'If I was a meme, which one am I?' },
  { id: '157', category: 'fun', text: 'What is your honest hot take about something I love that you secretly disagree with?' },
  { id: '158', category: 'fun', text: 'If we had a joint bank account for chaos, what would I spend the most on?' },
  { id: '159', category: 'fun', text: 'What is one thing about me that would genuinely surprise my own mother?' },
  { id: '160', category: 'fun', text: 'If you had to get a tattoo of something that represents me, what is it and where does it go?' },

  // GAME (continued)
  { id: '161', category: 'game', text: 'We each type one word to start a story, back and forth. First one to get weird loses.' },
  { id: '162', category: 'game', text: '20 questions. I am thinking of something and you have yes or no only.' },
  { id: '163', category: 'game', text: 'Two truths and a lie. Go. I will guess which one is the lie.' },
  { id: '164', category: 'game', text: 'Song lyrics hot potato. I start, you finish the next line, no Googling.' },
  { id: '165', category: 'game', text: 'Name 5 things in your room right now in under 10 seconds. Go.' },
  { id: '166', category: 'game', text: 'Rapid fire. I ask, you answer in 3 words max. No pausing.' },
  { id: '167', category: 'game', text: 'We each type our ideal version of tomorrow in one sentence. Share and compare.' },
  { id: '168', category: 'game', text: 'Emoji story. Tell me about your day using only 5 emojis. I will guess what happened.' },
  { id: '169', category: 'game', text: 'Type the first word that comes to mind when I say: us.' },
  { id: '170', category: 'game', text: 'Best 2-out-of-3 would you rather. I ask, you answer, then we switch.' },
  { id: '171', category: 'game', text: 'We both type what we think the other person is doing right now. Reveal at the same time.' },
  { id: '172', category: 'game', text: 'Name something red in your room before I count to 5. 5... 4... 3...' },
  { id: '173', category: 'game', text: 'The alphabet game. We take turns naming things we will do together, one per letter, A to Z.' },
  { id: '174', category: 'game', text: 'Type a number between 1 and 100. Closer to mine without going over wins a forehead kiss.' },
  { id: '175', category: 'game', text: 'Mirror game. Whatever I type next, you type the exact opposite feeling.' },

  // MEMORY (continued)
  { id: '176', category: 'memory', text: 'What is the exact moment you knew this was real and not just a feeling?' },
  { id: '177', category: 'memory', text: 'What is the most random thing that reminds you of me in your everyday life?' },
  { id: '178', category: 'memory', text: 'What is something I said once as a joke that turned out to be true?' },
  { id: '179', category: 'memory', text: 'Describe the first time you heard my voice. What did you notice?' },
  { id: '180', category: 'memory', text: 'What is the longest we have gone without talking and what did that feel like?' },
  { id: '181', category: 'memory', text: 'What is a photo of us you wish existed but never got taken?' },
  { id: '182', category: 'memory', text: 'What is something from the early days of us that you miss?' },
  { id: '183', category: 'memory', text: 'What is a moment where I showed up for you when you did not even ask?' },
  { id: '184', category: 'memory', text: 'What was going through your head the first time you typed I love you?' },
  { id: '185', category: 'memory', text: 'What is a fight we had that you are glad we worked through?' },
  { id: '186', category: 'memory', text: 'What is a version of us from a year ago you would go back and reassure?' },
  { id: '187', category: 'memory', text: 'What is the strangest or funniest coincidence in our story?' },
  { id: '188', category: 'memory', text: 'What is a compliment I gave you once that you still think about?' },
  { id: '189', category: 'memory', text: 'What is the first trip or outing you remember planning together and how did it go?' },
  { id: '190', category: 'memory', text: 'What is one thing about the beginning of us that you want to hold onto forever?' },

  // ACTION (continued)
  { id: '191', category: 'action', text: 'Record a 10-second voice note of complete silence just to feel like we are in the same room.' },
  { id: '192', category: 'action', text: 'Send me a screenshot of the last song you played without any context.' },
  { id: '193', category: 'action', text: 'Open your camera right now and take a photo of exactly where you are sitting. Send it.' },
  { id: '194', category: 'action', text: 'Type out a playlist name that describes your mood right now.' },
  { id: '195', category: 'action', text: 'Write me a letter to open the morning of the day we finally close the distance.' },
  { id: '196', category: 'action', text: 'Set a 1-minute timer and write me everything you feel without editing it.' },
  { id: '197', category: 'action', text: 'Find an old photo of yourself and send it. I want to see a version of you I never knew.' },
  { id: '198', category: 'action', text: 'Send me a voice note reading your favorite line from a book, show, or song.' },
  { id: '199', category: 'action', text: 'Look around and send me a photo of the thing closest to you right now.' },
  { id: '200', category: 'action', text: 'Type a one-sentence promise you are making to me right now.' },
  { id: '201', category: 'action', text: 'Send me a voice note of you saying good night in the most dramatic way you can.' },
  { id: '202', category: 'action', text: 'Type the name of the restaurant I have to take you to the moment we are in the same city.' },
  { id: '203', category: 'action', text: 'Screenshot a moment from your camera roll that made you think of me recently. Send it without explanation.' },
  { id: '204', category: 'action', text: 'Type a word that describes how you feel when you hear my name.' },
  { id: '205', category: 'action', text: 'Write the opening line of the story of us, as if it were the first page of a book.' },
];