import { type CardInfo } from './types';

export const LAST_CARDS: CardInfo[] = [
  // NAUGHTY (even more)
  { id: '341', category: 'naughty', text: 'What is the spiciest thing you want to whisper in my ear before we start?' },
  { id: '342', category: 'naughty', text: 'If you could only touch one part of my body for the rest of the night, what do you choose?' },
  { id: '343', category: 'naughty', text: 'Describe exactly how you would tease me until I beg.' },
  { id: '344', category: 'naughty', text: 'What is your favorite dirty word and why does it work on you?' },
  { id: '345', category: 'naughty', text: 'If we did it in front of a mirror, what would you want to see?' },
  { id: '346', category: 'naughty', text: 'What is your favorite place on my body to kiss and how hard?' },
  { id: '347', category: 'naughty', text: 'What is the boldest thing you have ever done when we were on video call?' },
  { id: '348', category: 'naughty', text: 'Describe what you would do if I told you I cannot sleep until you help.' },
  { id: '349', category: 'naughty', text: 'What is the naughtiest thing you have ever done in your parents house when they were home?' },
  { id: '350', category: 'naughty', text: 'If you could make a custom toy for us, what would it look like and how would it work?' },
  { id: '351', category: 'naughty', text: 'What is your favorite way to wake me up and does it involve clothes?' },
  { id: '352', category: 'naughty', text: 'Describe what you would do if I seductively walked toward you right now.' },
  { id: '353', category: 'naughty', text: 'What is the hottest text conversation you have ever saved?' },
  { id: '354', category: 'naughty', text: 'If you had one hour alone with me, how would you spend those 60 minutes?' },
  { id: '355', category: 'naughty', text: 'What is something you want to do to me that you think about when you should be sleeping?' },
  { id: '356', category: 'naughty', text: 'Tell me exactly what to do to you and I will do my best to follow instructions.' },
  { id: '357', category: 'naughty', text: 'What is the quickest way you have ever gotten turned on by just a text from me?' },
  { id: '358', category: 'naughty', text: 'Describe the hottest dream you have ever had about us.' },
  { id: '359', category: 'naughty', text: 'What is your favorite position to finish in and why does it hit different?' },
  { id: '360', category: 'naughty', text: 'If I was blindfolded, where would you touch first and what would you whisper?' },
  { id: '361', category: 'naughty', text: 'What is the messiest we have ever gotten and what was the clean up like?' },
  { id: '362', category: 'naughty', text: 'Describe exactly what you want to do to me after we have not seen each other for a while.' },
  { id: '363', category: 'naughty', text: 'What is your favorite outfit of mine to take off and in what order?' },
  { id: '364', category: 'naughty', text: 'How long can you last if I do not stop and why will it be hard?' },
  { id: '365', category: 'naughty', text: 'What is that one specific thing I do with my hands that destroys you?' },
  { id: '366', category: 'naughty', text: 'If I video called you right now ready to go, what is the first thing you do?' },
  { id: '367', category: 'naughty', text: 'What is the dirtiest sentence I have ever said to you that still makes you blush?' },
  { id: '368', category: 'naughty', text: 'Describe the perfect night in with me from the moment I walk in the door.' },
  { id: '369', category: 'naughty', text: 'What is your count and be honest, how many times this week alone?' },
  { id: '370', category: 'naughty', text: 'Where would you leave the hickey that would get me in trouble at work?' },
  { id: '371', category: 'naughty', text: 'If you could make me come right now with just your words, what would you say?' },
  { id: '372', category: 'naughty', text: 'What is your favorite dirty talk phrase?' },
  { id: '373', category: 'naughty', text: 'How many rounds can you go in one night?' },
  { id: '374', category: 'naughty', text: 'What is your biggest turn on when it comes to me?' },
  { id: '375', category: 'naughty', text: 'Where is the most public place we have ever done it?' },
  { id: '376', category: 'naughty', text: 'What is the best thing about our sex life?' },
  { id: '377', category: 'naughty', text: 'If we could film ourselves, what moment would you want replayed?' },
  { id: '378', category: 'naughty', text: 'What is your favorite time of day to be intimate?' },
  { id: '379', category: 'naughty', text: 'How do you feel after we finish? Be honest.' },
  { id: '380', category: 'naughty', text: 'What is one fantasy you want to act out?' },
  { id: '381', category: 'naughty', text: 'What is the best surprise you have planned for me?' },
  { id: '382', category: 'naughty', text: 'Describe what your dream night with me looks like.' },
  { id: '383', category: 'naughty', text: 'What makes you feel the most desired by me?' },
  { id: '384', category: 'naughty', text: 'If we used a blindfold, what would you do?' },
  { id: '385', category: 'naughty', text: 'What is the most romantic thing I have ever done for you in bed?' },
  { id: '386', category: 'naughty', text: 'What position do you want to try the most?' },
  { id: '387', category: 'naughty', text: 'How often do you think about me sexually?' },
  { id: '388', category: 'naughty', text: 'What is the most vulnerable you have ever been with me?' },
  { id: '389', category: 'naughty', text: 'What makes you feel safe with me in bed?' },
  { id: '390', category: 'naughty', text: 'Describe your perfect build up to intimacy.' },
  { id: '391', category: 'naughty', text: 'What is one thing we have never tried?' },
  { id: '392', category: 'naughty', text: 'If I watched you, what would you do?' },
  { id: '393', category: 'naughty', text: 'What is the hottest thing I have ever said to you?' },
  { id: '394', category: 'naughty', text: 'How do you want to be touched tonight?' },
  { id: '395', category: 'naughty', text: 'What sound do you make when you finish?' },
  { id: '396', category: 'naughty', text: 'What is your favorite part of my body?' },
  { id: '397', category: 'naughty', text: 'What turns you on the most about me?' },
  { id: '398', category: 'naughty', text: 'Tell me your deep dark fantasy.' },
  { id: '399', category: 'naughty', text: 'What is your biggest insecurity in bed?' },
  { id: '400', category: 'naughty', text: 'If I was shy, how would you make me comfortable?' },

  // FUN (even more)
  { id: '401', category: 'fun', text: 'What is the most ridiculous thing you have defending me about?' },
  { id: '402', category: 'fun', text: 'If we had a theme song that was an 80s ballad, what would be the most embarrassing lyric?' },
  { id: '403', category: 'fun', text: 'What is a inside joke we have that would make no sense to anyone else?' },
  { id: '404', category: 'fun', text: 'If I was a car, what make and model would I be and is it a compliment?' },
  { id: '405', category: 'fun', text: 'What is the most extra thing you have done just to impress me?' },
  { id: '406', category: 'fun', text: 'If we made a scrapbook together, what would the first page say?' },
  { id: '407', category: 'fun', text: 'What is your least favorite thing about my cooking?' },
  { id: '408', category: 'fun', text: 'If we were in a boy band, what would be our worst music video?' },
  { id: '409', category: 'fun', text: 'What is the most extra thing I have done that you secretly loved?' },
  { id: '410', category: 'fun', text: 'If we had to rename ourselves as a couple, what would our couple name be?' },
  { id: '411', category: 'fun', text: 'What is a movie trope we actually live out in our relationship?' },
  { id: '412', category: 'fun', text: 'If we had a dating bio for each other, what would we swipe left on?' },
  { id: '413', category: 'fun', text: 'What is your favorite thing about the way I sleep?' },
  { id: '414', category: 'fun', text: 'If we were fictional characters, what genre would our story be?' },
  { id: '415', category: 'fun', text: 'What is the most useless fact about me that you know?' },
  { id: '416', category: 'fun', text: 'How would you describe our relationship in 3 words?' },
  { id: '417', category: 'fun', text: 'What is our song and why?' },
  { id: '418', category: 'fun', text: 'If I was a super villain, what would my power be?' },
  { id: '419', category: 'fun', text: 'What is the pettiest thing you have saved about me?' },
  { id: '420', category: 'fun', text: 'What is something I do that makes you laugh?' },
  { id: '421', category: 'fun', text: 'If we had a theme park, what would the rides be called?' },
  { id: '422', category: 'fun', text: 'What is the most surprising thing about me?' },
  { id: '423', category: 'fun', text: 'If we were cartoon animals, what would we be?' },
  { id: '424', category: 'fun', text: 'What is the most random thing we have in common?' },
  { id: '425', category: 'fun', text: 'If we had a band, what would it be called?' },
  { id: '426', category: 'fun', text: 'What is the funniest thing I have ever said?' },
  { id: '427', category: 'fun', text: 'If I was a food, what would I be?' },
  { id: '428', category: 'fun', text: 'What makes our relationship unique?' },
  { id: '429', category: 'fun', text: 'What is the best inside joke we share?' },
  { id: '430', category: 'fun', text: 'If we did a photoshoot, what would be the vibe?' },
  { id: '431', category: 'fun', text: 'What is something I always get wrong?' },
  { id: '432', category: 'fun', text: 'What is the most iconic thing about us?' },
  { id: '433', category: 'fun', text: 'If we had a podcast name, what would it be?' },
  { id: '434', category: 'fun', text: 'What is the weirdest thing I do when alone?' },
  { id: '435', category: 'fun', text: 'What is our celebrity couple equivalent?' },
  { id: '436', category: 'fun', text: 'What is your favorite thing about my laugh?' },
  { id: '437', category: 'fun', text: 'If I was a color, what would I be?' },
  { id: '438', category: 'fun', text: 'What makes you laugh about us?' },
  { id: '439', category: 'fun', text: 'What is the weirdest thing we have done together?' },
  { id: '440', category: 'fun', text: 'What is your favorite memory of us today?' },

  // DEEP (even more)
  { id: '441', category: 'deep', text: 'What is a belief about love you had before me that I completely shattered?' },
  { id: '442', category: 'deep', text: 'When was the last time you cried because of how much you love me?' },
  { id: '443', category: 'deep', text: 'What is something about you that you think I would leave me for if I found out?' },
  { id: '444', category: 'deep', text: 'If we never worked out, what would you want me to know about why it was still worth it?' },
  { id: '445', category: 'deep', text: 'What is your honest, unfiltered expectation of what our life will look like in 5 years?' },
  { id: '446', category: 'deep', text: 'What is a part of your life I am not included in that you hold onto secretly?' },
  { id: '447', category: 'deep', text: 'What is something you have forgiven me for that you have not told me about?' },
  { id: '448', category: 'deep', text: 'If I died tomorrow, what is the one thing you would want to have told me but never did?' },
  { id: '449', category: 'deep', text: 'What is a promise you made to yourself about this relationship that you have not told me?' },
  { id: '450', category: 'deep', text: 'What is the most vulnerable thing you have ever said to me and how did it feel?' },
];