import { type CardInfo, type Category } from './types';

export const SPICY_CARDS: CardInfo[] = [
  { id: '77', category: 'spicy', text: 'What is your favorite memory of us in the bedroom?' },
  { id: '78', category: 'spicy', text: 'What is a secret fantasy you have been too shy to share?' },
  { id: '79', category: 'spicy', text: 'What is your absolute favorite spot to be kissed?' },
  { id: '80', category: 'spicy', text: 'What is something I do that instantly gets your attention?' },
  { id: '81', category: 'spicy', text: 'What do you think I look best in — or without?' },
  { id: '82', category: 'spicy', text: 'What is one thing you want to do the next time we meet?' },
  { id: '83', category: 'spicy', text: 'What kind of kiss do you miss the most from me?' },
  { id: '84', category: 'spicy', text: 'What is something subtle I do that you find really attractive?' },
  { id: '85', category: 'spicy', text: 'What kind of moment between us do you replay the most in your head?' },
  { id: '86', category: 'spicy', text: 'What do you think I underestimate about my own attractiveness?' },
  { id: '87', category: 'spicy', text: 'What is one thing you would want to do slowly with me next time we meet?' },
  { id: '88', category: 'spicy', text: 'What kind of closeness do you miss the most right now?' },
  { id: '89', category: 'spicy', text: 'What is something you have imagined about us that you have not told me yet?' },
  { id: '90', category: 'spicy', text: 'Describe the last dream you had about me.' },
  { id: '109', category: 'spicy', text: 'If we were stuck in a lift together for 20 minutes, how would we spend the time?' },
  { id: '110', category: 'spicy', text: 'What is the most explicit thing you have ever thought about doing to me?' },
  { id: '206', category: 'spicy', text: 'What is the most attractive thing about me that has absolutely nothing to do with looks?' },
  { id: '207', category: 'spicy', text: 'What is a look I give you that makes it genuinely difficult to stay composed?' },
  { id: '208', category: 'spicy', text: 'What is the most charged moment between us that we never acted on?' },
  { id: '209', category: 'spicy', text: 'If you had to seduce me using only words, what is the first sentence?' },
  { id: '210', category: 'spicy', text: 'What do I do with my voice that you find secretly electric?' },
  { id: '211', category: 'spicy', text: 'What is the most tension you have ever felt between us without anything happening?' },
  { id: '212', category: 'spicy', text: 'If you could feel my presence for just 5 minutes right now, how would you use it?' },
  { id: '213', category: 'spicy', text: 'What is the most attractive thing I have ever done completely by accident?' },
  { id: '214', category: 'spicy', text: 'What part of me do you think about when you are trying to focus on something else?' },
  { id: '215', category: 'spicy', text: 'What is something about the way I text that gets under your skin in the best way?' },
  { id: '216', category: 'spicy', text: 'If the distance disappeared for one night, what is the first thing we would not do?' },
  { id: '217', category: 'spicy', text: 'What is a version of me in your imagination that you have never told me about?' },
  { id: '218', category: 'spicy', text: 'What kind of tension between us do you love to build and not release?' },
  { id: '219', category: 'spicy', text: 'What does it feel like in your body when I tell you I miss you?' },
  { id: '220', category: 'spicy', text: 'If I showed up at your door right now at midnight, what would your face do before your words?' },
  { id: '221', category: 'spicy', text: 'What is something I wear or do that makes you forget what you were saying?' },
  { id: '222', category: 'spicy', text: 'What would it feel like to finally fall asleep in the same bed as me?' },
  { id: '223', category: 'spicy', text: 'What is the single most physically attractive moment you can remember between us?' },
  { id: '224', category: 'spicy', text: 'What is something you would want to do slowly and quietly together that is completely innocent but somehow deeply intimate?' },
  { id: '225', category: 'spicy', text: 'If you could hear my heartbeat right now, what do you imagine it sounds like?' },
];

export const NAUGHTY_CARDS: CardInfo[] = [
  { id: '91', category: 'naughty', text: 'Whisper something indecent in my ear.' },
  { id: '92', category: 'naughty', text: 'Where is the riskiest place you have ever wanted to do it?' },
  { id: '93', category: 'naughty', text: 'What article of my clothing drives you the craziest?' },
  { id: '94', category: 'naughty', text: 'If I was right in front of you right now, what is the first thing you would do?' },
  { id: '95', category: 'naughty', text: 'Describe how you would distract me if I was trying to focus.' },
  { id: '96', category: 'naughty', text: 'What is something you would whisper to me if no one could hear?' },
  { id: '97', category: 'naughty', text: 'What is your favorite way to tease me, and do you think it always works?' },
  { id: '98', category: 'naughty', text: 'What is something you want me to do more often?' },
  { id: '99', category: 'naughty', text: 'What is something you think about when you miss me late at night?' },
  { id: '100', category: 'naughty', text: 'What is one way you would try to distract me if we were completely alone together?' },
  { id: '101', category: 'naughty', text: 'What kind of teasing from me makes it hardest for you to keep your composure?' },
  { id: '102', category: 'naughty', text: 'If you could have me any way you wanted tonight, walk me through it.' },
  { id: '103', category: 'naughty', text: 'What do I do that makes it hard for you to keep your hands to yourself?' },
  { id: '104', category: 'naughty', text: 'Describe exactly how you would kiss me right now if you could.' },
  { id: '105', category: 'naughty', text: 'What is your biggest guilty pleasure when it comes to me?' },
  { id: '106', category: 'naughty', text: 'What would you do if you woke up and I was already next to you?' },
  { id: '107', category: 'naughty', text: 'What is one outfit you want to see me in — or out of?' },
  { id: '108', category: 'naughty', text: 'What is a scenario you have imagined about us that you have never admitted?' },
  { id: '111', category: 'naughty', text: 'Send me a photo of your favorite "view" of me, even if it\'s NSFW.' },
  { id: '112', category: 'naughty', text: 'Describe the exact sensations you want to feel the next time we are naked together.' },
  { id: '113', category: 'naughty', text: 'If you could use any toy or accessory on me, what would it be and how?' },
  { id: '114', category: 'naughty', text: 'What part of my body do you crave tasting the most right now?' },
  { id: '115', category: 'naughty', text: 'How do you like to be touched when you\'re already on the edge?' },
  { id: '116', category: 'naughty', text: 'Tell me exactly what you want me to do to you until you can\'t take it anymore.' },
  { id: '117', category: 'naughty', text: 'What is your favorite position, and why does it feel the best with me?' },
  { id: '118', category: 'naughty', text: 'Describe a time you were thinking about me while you were "taking care" of yourself.' },
  { id: '119', category: 'naughty', text: 'If I told you to get on your knees right now, what would your response be?' },
  { id: '120', category: 'naughty', text: 'What is a dirty habit you have that you think would surprise me?' },
];