import { type CardInfo } from './types';

export const MORE_SPICY_CARDS: CardInfo[] = [
  { id: '226', category: 'spicy', text: 'What is the filthiest thought you have had about me this week?' },
  { id: '227', category: 'spicy', text: 'Describe in explicit detail exactly how you would take my clothes off if you were here.' },
  { id: '228', category: 'spicy', text: 'What is a sound you want to hear me make that you have not heard yet?' },
  { id: '229', category: 'spicy', text: 'Walk me through exactly what you would do to me if I told you I had 30 minutes and no one else home.' },
  { id: '230', category: 'spicy', text: 'What is the dirtiest thing you have ever wanted to say to me mid-act but held back?' },
  { id: '231', category: 'spicy', text: 'If I sent you a photo right now that was completely unfiltered, what would you ask me to do next?' },
  { id: '232', category: 'spicy', text: 'Describe the most explicit dream you have had about me in as much detail as you remember.' },
  { id: '233', category: 'spicy', text: 'What is something specific about my body that makes you lose control of your thoughts?' },
  { id: '234', category: 'spicy', text: 'If you could have me in any position for as long as you wanted, what are you choosing and why?' },
  { id: '235', category: 'spicy', text: 'What would you do to me if you knew I was already worked up before you even touched me?' },
  { id: '236', category: 'spicy', text: 'What is the most explicit voice note you have ever wanted to send me?' },
  { id: '237', category: 'spicy', text: 'Where exactly would your hands go first if no one was watching and we had all the time in the world?' },
  { id: '238', category: 'spicy', text: 'What is something specific you want to do to me that requires no rush and no clothes?' },
  { id: '239', category: 'spicy', text: 'Describe what you want me to do with my mouth right now.' },
  { id: '240', category: 'spicy', text: 'What is the exact phrase you would whisper to me in the dark that would completely undo me?' },
  { id: '241', category: 'spicy', text: 'What is your most indulgent fantasy about us that you replay when you are alone?' },
  { id: '242', category: 'spicy', text: 'If I gave you full permission to do whatever you wanted to me for one hour, give me the unedited version.' },
  { id: '243', category: 'spicy', text: 'What is the most explicit compliment you have been too shy to say out loud?' },
  { id: '244', category: 'spicy', text: 'What would you want to hear me say while you are touching me?' },
  { id: '245', category: 'spicy', text: 'What is something you want to try with me that you have never tried with anyone else?' },
  { id: '246', category: 'spicy', text: 'Describe what finishing together would look and feel like in as much detail as you want.' },
  { id: '247', category: 'spicy', text: 'What is the most specific body part you want your mouth on and what exactly would you do?' },
  { id: '248', category: 'spicy', text: 'If I called you right now completely out of breath, what do you think would have just happened?' },
  { id: '249', category: 'spicy', text: 'What is the scenario you replay most when you are taking care of yourself and I am the reason?' },
  { id: '250', category: 'spicy', text: 'Write me a short paragraph of the filthiest thing you want to do to me the second the distance is gone.' },

  // MORE NAUGHTY
  { id: '251', category: 'naughty', text: 'What is your go-to fantasy when you are alone that you have never told me?' },
  { id: '252', category: 'naughty', text: 'Describe exactly what you would do if we were stuck together for 24 hours with nothing to do.' },
  { id: '253', category: 'naughty', text: 'What is the most intimate thing you have ever done in a public place?' },
  { id: '254', category: 'naughty', text: 'If you could control my body for 10 minutes, what would you make me do?' },
  { id: '255', category: 'naughty', text: 'What is the longest you have ever edged and why was it for me?' },
  { id: '256', category: 'naughty', text: 'Describe in detail what you want to do to every single part of my body.' },
  { id: '257', category: 'naughty', text: 'What is something about sex with me that you have never said out loud but want me to know?' },
  { id: '258', category: 'naughty', text: 'Error Card' },
  { id: '259', category: 'naughty', text: 'What costume or outfit do you want to see me in that is not for any occasion?' },
  { id: '260', category: 'naughty', text: 'What is your favorite way to be touched and how do you want me to do it right now?' },
  { id: '261', category: 'naughty', text: 'Describe exactly what you would do if we had all night with zero interruptions.' },
  { id: '262', category: 'naughty', text: 'What is the most sexually frustrating thing about the distance for you?' },
  { id: '263', category: 'naughty', text: 'What is the last thing you thought about before you fell asleep last night involving me?' },
  { id: '264', category: 'naughty', text: 'If I was inside you right now, what position would you want us in and what would you want to say?' },
  { id: '265', category: 'naughty', text: 'What part of my body do you want to taste the most and what exactly would you do with it?' },
  { id: '266', category: 'naughty', text: 'Tell me exactly how you would make love to me slowly from start to finish.' },
  { id: '267', category: 'naughty', text: 'What is the naughtiest thing you want to whisper in my ear while we do it?' },
  { id: '268', category: 'naughty', text: 'What toy would you want to use on me first and how would you use it?' },
  { id: '269', category: 'naughty', text: 'How many times have you came thinking about me this month? Be honest.' },
  { id: '270', category: 'naughty', text: 'What is your favorite time of day to do it and why?' },
  { id: '271', category: 'naughty', text: 'Describe what you want our first time to be like when we finally meet.' },
  { id: '272', category: 'naughty', text: 'What is a kink you have that you want to explore with me?' },
  { id: '273', category: 'naughty', text: 'What would you do if I sent you a spicy photo right now?' },
  { id: '274', category: 'naughty', text: 'What position are we doing the moment we are together and why?' },
  { id: '275', category: 'naughty', text: 'Where is the dirtiest place we could possibly do it and would we risk it?' },
  { id: '276', category: 'naughty', text: 'What sound do you most want to hear me make in bed?' },
  { id: '277', category: 'naughty', text: 'Tell me exactly what you would do if I slept over at your place tonight.' },
  { id: '278', category: 'naughty', text: 'What is your ultimate fantasy involving both of us?' },
  { id: '279', category: 'naughty', text: 'How do you want me to dominate you?' },
  { id: '280', category: 'naughty', text: 'What is your count and how many times can you make me finish?' },

  // EVEN MORE FUN
  { id: '281', category: 'fun', text: 'If we had a couple Instagram, what would our most embarrassing post be?' },
  { id: '282', category: 'fun', text: 'What is the most stupid reason you have ever been mad at me?' },
  { id: '283', category: 'fun', text: 'If I was a potato, what type of potato would I be and why?' },
  { id: '284', category: 'fun', text: 'What would our wedding cake look like if it was designed by a toddler?' },
  { id: '285', category: 'fun', text: 'If you had to explain our relationship to an alien, which pop culture reference would you use?' },
  { id: '286', category: 'fun', text: 'What is the most ridiculous thing you have typed to me and then deleted?' },
  { id: '287', category: 'fun', text: 'If we made a TikTok, what would its description say?' },
  { id: '288', category: 'fun', text: 'What is my most predictable bad habit that I refuse to admit?' },
  { id: '289', category: 'fun', text: 'If we competed in the Olympics of relationships, what event would we absolutely win?' },
  { id: '290', category: 'fun', text: 'What is the weirdest thing you have eaten just because I recommended it?' },
  { id: '291', category: 'fun', text: 'If we were in a reality TV show, what dramatic thing would happen in episode 3?' },
  { id: '292', category: 'fun', text: 'What is a phrase I say that has become hauntingly in your head?' },
  { id: '293', category: 'fun', text: 'If I was a video game, what difficulty level would I be on and why?' },
  { id: '294', category: 'fun', text: 'What is the most chaos-inducing thing you would do if I gave you my phone for 5 minutes?' },
  { id: '295', category: 'fun', text: 'If we had a joint bank account for dates, what would be the weirdest purchase we would make?' },
  { id: '296', category: 'fun', text: 'What is one thing about me that would make my future kids confused about?' },
  { id: '297', category: 'fun', text: 'If we met on a dating app, what would your opening line be?' },
  { id: '298', category: 'fun', text: 'What is the most unhinged thing you have done while missing me?' },
  { id: '299', category: 'fun', text: 'If we were cartoon characters, what would our catchphrase be?' },
  { id: '300', category: 'fun', text: 'What is something I do that would make a psychologist concerned?' },
  { id: '301', category: 'fun', text: 'If I was a smell, what would I smell like and it is not a compliment?' },
  { id: '302', category: 'fun', text: 'What is the worst "we were thinking about each other" text you have ever sent?' },
  { id: '303', category: 'fun', text: 'If we had a couples costume, what would it be and which one of us would complain more?' },
  { id: '304', category: 'fun', text: 'What is something I do that works on you but should not?' },
  { id: '305', category: 'fun', text: 'If you could make one of my habits a crime, what would be the punishment?' },
  { id: '306', category: 'fun', text: 'What is the most embarrassing notification sound you have set for me and do not lie?' },
  { id: '307', category: 'fun', text: 'If our love story was a trilogy, what would the second movie be called and it has to be cheesy?' },
  { id: '308', category: 'fun', text: 'What is the pettiest reason you have ever been mad at me?' },
  { id: '309', category: 'fun', text: 'If we lived in a sitcom, what would be the episode where everything goes wrong?' },
  { id: '310', category: 'fun', text: 'What is something I do when I think you are not looking that you act like you did not see?' },

  // EVEN MORE DEEP
  { id: '311', category: 'deep', text: 'What is a belief about love you had before me that I completely shattered?' },
  { id: '312', category: 'deep', text: 'When was the last time you cried because of how much you love me?' },
  { id: '313', category: 'deep', text: 'What is something about you that you think I would leave me for if I found out?' },
  { id: '314', category: 'deep', text: 'If we never worked out, what would you want me to know about why it was still worth it?' },
  { id: '315', category: 'deep', text: 'What is your honest, unfiltered expectation of what our life will look like in 5 years?' },
  { id: '316', category: 'deep', text: 'What is a part of your life I am not included in that you hold onto secretly?' },
  { id: '317', category: 'deep', text: 'What is something you have forgiven me for that you have not told me about?' },
  { id: '318', category: 'deep', text: 'If I died tomorrow, what is the one thing you would want to have told me but never did?' },
  { id: '319', category: 'deep', text: 'What is a promise you made to yourself about this relationship that you have not told me?' },
  { id: '320', category: 'deep', text: 'What is the most vulnerable thing you have ever said to me and how did it feel?' },
  { id: '321', category: 'deep', text: 'What is something you pretend not to care about but secretly keeps you up at night?' },
  { id: '322', category: 'deep', text: 'Do you actually believe we are going to work out long-term? Be honest.' },
  { id: '323', category: 'deep', text: 'What is the worst thing you have ever thought about doing when you are mad at me?' },
  { id: '324', category: 'deep', text: 'What is a moment where you almost gave up on us but could not?' },
  { id: '325', category: 'deep', text: 'What is something you are jealous of other couples for that we do not have?' },
  { id: '326', category: 'deep', text: 'What is your biggest insecurity about this relationship?' },
  { id: '327', category: 'deep', text: 'If we had to go back to the beginning knowing what you know now, would you still choose me?' },
  { id: '328', category: 'deep', text: 'What is something you have stopped wanting because it feels impossible with the distance?' },
  { id: '329', category: 'deep', text: 'What is the most beautiful thing someone has ever said to you that was not me?' },
  { id: '330', category: 'deep', text: 'What is a conversation with me that changed something fundamental about you?' },
  { id: '331', category: 'deep', text: 'What is the one thing about this relationship that still surprises you about yourself?' },
  { id: '332', category: 'deep', text: 'What is something you have learned about love that you never learned from anyone else?' },
  { id: '333', category: 'deep', text: 'What is a moment when you realized you would wait for me no matter how long it takes?' },
  { id: '334', category: 'deep', text: 'What is your unfiltered opinion about the way I show love?' },
  { id: '335', category: 'deep', text: 'What is a fear you have that you have not told me because you do not want to worry me?' },
  { id: '336', category: 'deep', text: 'What is the most selfless thing you have ever done for us?' },
  { id: '337', category: 'deep', text: 'What is something you wish we could do differently but feel stuck about?' },
  { id: '338', category: 'deep', text: 'What does "forever" actually look like in your mind?' },
  { id: '339', category: 'deep', text: 'If you could change one thing about how we handle conflict, what would it be?' },
  { id: '340', category: 'deep', text: 'What is a version of our future you are secretly excited about but too scared to admit?' },
];